# Generated by Django 2.1.7 on 2019-03-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='filter',
            field=models.CharField(max_length=200, null=True, verbose_name='Filter'),
        ),
    ]
