# Generated by Django 2.1.7 on 2019-03-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_auto_20190304_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='source_batch_sql',
            field=models.CharField(max_length=4000, verbose_name='Source Batch SQL'),
        ),
    ]
