# Generated by Django 2.0.1 on 2019-04-17 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_auto_20190417_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedLoadId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='shares_loadid_with',
        ),
        migrations.AddField(
            model_name='job',
            name='full_import',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='job',
            name='shares_loadid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sharing_jobs', to='etl.SharedLoadId'),
        ),
    ]
