# Generated by Django 2.0.1 on 2019-04-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0007_auto_20190417_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='shares_loadid',
            new_name='shared_loadid',
        ),
        migrations.AlterField(
            model_name='job',
            name='full_import',
            field=models.BooleanField(default=True, verbose_name='Full Import'),
        ),
    ]
